# docker-compose -f deploy/docker-compose/docker-compose.yaml up
version: "3"
services:
  workflow-server:
    image: workflow-server:latest
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: TABLE
      MYSQL_USER: ROOT
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
